apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: 'https://github.com/moshe322/nodejs-ecommerce.git'
    path: '.'
    targetRevision: 'HEAD'
  
  destination:
    namespace: default
    server: 'https://12D82A849D1AB20CFBDDF64FBFC311AD.gr7.us-east-1.eks.amazonaws.com'
  
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

