apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'  # This is the internal Kubernetes service DNS
    namespace: default
  source:
    repoURL: 'https://github.com/moshe322/nodejs-ecommerce.git'
    path: '.'
    targetRevision: 'main'  # or 'master', depending on your branch
  project: default
